[build]
  command = "npm install --legacy-peer-deps --omit=optional && npm run build"
  publish = "dist" # or your build output directory

[build.environment]
  NODE_VERSION = "20.12.2"

# Keep your existing build settings below
# ...existing code... 