[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.12.2"

# Keep your existing build settings below
# ...existing code... 